swagger: '2.0'
info:
  title: Checkings Account API
  version: 1.0.0
  description: API for managing checkings accounts
paths:
  /transactions:
    get:
      summary: returns all transactions from a specified account
      description: Retrieves all transactions for a given account
      parameters:
        - name: accountId
          in: query
          description: Account number needed to list transactions
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successfully returned all transactions
          schema:
            type: array
            items:
              type: object
              properties:
                transactionId:
                  type: integer
                  format: int64
                  description: The ID of a transaction
                date:
                  type: string
                  description: The date on which the transaction occurred
                amount:
                  type: number
                  format: double
                  description: The total amount of the transaction
                transactionType:
                  type: string
                  description: What type the transaction falls into
                comment:
                  type: string
                  description: Describing the transaction further if needed

  /createAccount:
    post:
      summary: Create a new checkings account
      parameters:
        - name: customerName
          in: formData
          description: Customer's name
          required: true
          type: string
        - name: personID
          in: formData
          description: Unique person ID
          required: true
          type: string
        - name: stateofResidence
          in: formData
          description: State of residence
          required: true
          type: string
      responses:
        '200':
          description: Checkings account successfully created.
          schema:
            type: object
            properties:
              accountId:
                type: integer
                format: int64

  /createTransaction:
    patch:
      summary: Creates a transaction that is a applied to a specified account
      description: the newly created transaction is applied
      parameters:
        - name: accountId
          in: query
          description: Account number needed to retreive transactions
          required: true
          type: integer
          format: int64
        - name: amount
          in: formData
          description: Total amount needed to apply to the account
          required: true
          type: number
          format: double
        - name: transactionType
          in: formData
          description: Debit or Credit type
          required: true
          type: string
        - name: comment
          in: formData
          description: Describes what the transaction is related to
          required: true
          type: string
      responses:
        '200':
          description: Successfully created a new trasnaction
          schema:
            type: object
            properties:
              transactionId:
                type: integer
                format: int64
                description: The ID of a transaction
              accountBalance:
                type: number
                format: double
                description: The total balance of the account

  /accounts:
    get:
      summary: returns all checking accounts.
      responses:
        '200':
          schema:
            type: array
            description: returns a list of all accounts
            items:
              type: object
              properties:
                customerName:
                  type: string
                  description: Name of the customer on the account
                customerId:
                  type: integer
                  format: int64
                  description: The ID of the customer
                accountNum:
                  type: integer
                  format: int64
                  description: The number of the account
                statusAccount:
                  type: string
                  description: returns the status of the account
                registeredDate:
                  type: string
                  description: returns the date on which the account was opened
                accountBalance:
                  type: number
                  format: double
                  description: The total balance of the account

  /changeAccountStatus:
    put:
      summary: Changes the status of a specified account
      parameters:
        - name: accountNum
          in: formData
          description: Account number specified for changing its statuses
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successfully changed status of account
          schema:
            type: object
            properties:
              status:
                type: string
                description: returns the status of the account

